#!/usr/bin/env python3
"""
Environment file generator for AI CLI.

Generates a .env file with default values from the Pydantic settings fields.
This makes it easy for users to see all available configuration options.
"""

import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent
PROJECT_ROOT = SCRIPT_DIR.parent
sys.path.insert(0, str(PROJECT_ROOT / "src"))


def get_field_info(model_class, env_prefix: str = "") -> list[dict]:
    """Extract field information from a Pydantic model."""
    from pydantic_core import PydanticUndefined

    fields_info = []

    for field_name, field_info in model_class.model_fields.items():
        env_name = field_name.upper()

        if field_info.validation_alias:
            env_name = str(field_info.validation_alias)
        elif env_prefix:
            env_name = f"{env_prefix}{field_name.upper()}"

        default = field_info.default
        is_required = default is PydanticUndefined

        if is_required:
            default = ""
        elif default is None:
            default = ""

        description = field_info.description or ""

        fields_info.append(
            {
                "env_name": env_name,
                "default": default,
                "description": description,
                "required": is_required,
            }
        )

    return fields_info


def generate_env_content(api_key: str = "") -> str:
    """Generate the .env file content from Pydantic settings."""
    from ai_cli.config.settings import AIConfig, GitConfig

    lines = [
        "# ============================================",
        "# AI CLI Configuration",
        "# Generated by scripts/env-gen.py",
        "# ============================================",
        "",
        "# --------------------------------------------",
        "# AI Service Configuration",
        "# --------------------------------------------",
    ]

    ai_fields = get_field_info(AIConfig)
    for field in ai_fields:
        if field["description"]:
            lines.append(f"# {field['description']}")
        if field["required"]:
            lines.append("# (Required)")

        # Use provided API key for GEMINI_API_KEY field
        if field["env_name"] == "GEMINI_API_KEY" and api_key:
            value = api_key
        else:
            value = field["default"]

        lines.append(f"{field['env_name']}={value}")
        lines.append("")

    lines.append("# --------------------------------------------")
    lines.append("# Git Configuration")
    lines.append("# --------------------------------------------")

    git_fields = get_field_info(GitConfig, env_prefix="GIT_")
    for field in git_fields:
        if field["description"]:
            lines.append(f"# {field['description']}")
        lines.append(f"{field['env_name']}={field['default']}")
        lines.append("")

    lines.append("# --------------------------------------------")
    lines.append("# Application Configuration")
    lines.append("# --------------------------------------------")

    app_fields = [
        {"env_name": "DEBUG", "default": "false", "description": "Enable debug mode"},
        {
            "env_name": "LOG_LEVEL",
            "default": "INFO",
            "description": "Logging level (DEBUG, INFO, WARNING, ERROR)",
        },
    ]
    for field in app_fields:
        if field["description"]:
            lines.append(f"# {field['description']}")
        lines.append(f"{field['env_name']}={field['default']}")
        lines.append("")

    return "\n".join(lines)


def get_current_api_key(config_path: Path) -> str:
    """Read the current API key from an existing config file."""
    if not config_path.exists():
        return ""

    try:
        content = config_path.read_text()
        for line in content.split("\n"):
            if line.startswith("GEMINI_API_KEY="):
                return line.split("=", 1)[1].strip()
    except Exception:
        pass
    return ""


def set_api_key(api_key: str, global_config: bool = True) -> None:
    """Set or update the API key in the config file."""
    if global_config:
        config_path = Path.home() / ".config" / "ai-cli" / ".env"
        config_path.parent.mkdir(parents=True, exist_ok=True)
    else:
        config_path = Path(".env")

    # If file exists, update just the API key line
    if config_path.exists():
        content = config_path.read_text()
        lines = content.split("\n")
        updated = False

        for i, line in enumerate(lines):
            if line.startswith("GEMINI_API_KEY="):
                lines[i] = f"GEMINI_API_KEY={api_key}"
                updated = True
                break

        if updated:
            config_path.write_text("\n".join(lines))
            print(f"✅ Updated API key in {config_path}")
            return

    # If file doesn't exist or key not found, generate new file
    content = generate_env_content(api_key)
    config_path.write_text(content)
    print(f"✅ Generated {config_path} with API key")


def interactive_setup() -> None:
    """Run interactive setup to configure ai-cli."""
    print("🤖 AI CLI Setup")
    print("=" * 40)
    print()

    global_path = Path.home() / ".config" / "ai-cli" / ".env"
    current_key = get_current_api_key(global_path)

    if current_key:
        masked_key = current_key[:8] + "..." + current_key[-4:] if len(current_key) > 12 else "***"
        print(f"Current API key: {masked_key}")
        print()
        response = input("Update API key? [y/N]: ").strip().lower()
        if response != "y":
            print("No changes made.")
            return

    print()
    print("Get your API key from: https://makersuite.google.com/app/apikey")
    print()

    api_key = input("Enter your GEMINI_API_KEY: ").strip()

    if not api_key:
        print("❌ No API key provided. Aborted.")
        sys.exit(1)

    set_api_key(api_key, global_config=True)
    print()
    print("🎉 Setup complete! You can now use ai-cli from any project.")
    print()
    print("Quick start:")
    print("  ai-cli smart-commit      # AI-powered commit")
    print("  ai-cli create-pr         # Create PR from branch")
    print("  ai-cli --help            # See all commands")


def main():
    """Main function to generate the .env file."""
    import argparse

    parser = argparse.ArgumentParser(
        description="Generate .env file with default configuration values"
    )
    parser.add_argument(
        "-o",
        "--output",
        type=str,
        default=".env",
        help="Output file path (default: .env)",
    )
    parser.add_argument(
        "-f", "--force", action="store_true", help="Overwrite existing file without prompting"
    )
    parser.add_argument(
        "--stdout", action="store_true", help="Print to stdout instead of writing to file"
    )
    parser.add_argument(
        "--global",
        dest="global_config",
        action="store_true",
        help="Generate in global config directory (~/.config/ai-cli/)",
    )
    parser.add_argument(
        "--api-key",
        type=str,
        help="Set the GEMINI_API_KEY directly",
    )
    parser.add_argument(
        "--setup",
        action="store_true",
        help="Run interactive setup wizard",
    )

    args = parser.parse_args()

    # Interactive setup mode
    if args.setup:
        interactive_setup()
        return

    # Direct API key setting
    if args.api_key:
        set_api_key(args.api_key, global_config=args.global_config)
        return

    # Generate content
    content = generate_env_content()

    if args.global_config:
        output_path = Path.home() / ".config" / "ai-cli" / ".env"
        output_path.parent.mkdir(parents=True, exist_ok=True)
    else:
        output_path = Path(args.output)

    if args.stdout:
        print(content)
        return

    if output_path.exists() and not args.force:
        response = input(f"File '{output_path}' already exists. Overwrite? [y/N]: ")
        if response.lower() != "y":
            print("Aborted.")
            sys.exit(1)

    output_path.write_text(content)
    print(f"✅ Generated {output_path}")
    print(f"📝 Edit the file and set your GEMINI_API_KEY")


if __name__ == "__main__":
    main()

